version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run dashboard/advanced_dashboard.py
    environment:
      - PYTHONPATH=/app

  producer:
    build: .
    volumes:
      - .:/app
    command: python -m market_data.data.producer
    depends_on:
      - app
    environment:
      - PYTHONPATH=/app
      - DATABASE_PATH=/app/finance.db
